Receipts streamline
FlipsideCrypto/aurora-models pull request #20
Opened 2023-07-24 15:59 UTC by WHYTEWYLL

adding Retry logic

2023-07-24 17:04 UTC, forgxyz commented on models/silver/retry/_pending_status.sql
> +    tx_hash
Compilation error, tx_hash is not in the subject CTE

2023-07-24 17:04 UTC, forgxyz requested changes
`_pending_status` model does not compile

2023-07-25 00:17 UTC, forgxyz commented on models/silver/streamline/realtime/streamline__blocks_realtime.sql
> +    block_number,
We need a DISTINCT here. As TX_HASH was added to the ephemeral model, we'll likely get multiple TXs per block

2023-07-25 00:19 UTC, forgxyz commented on models/silver/streamline/realtime/streamline__transactions_realtime.sql
> +    block_number,
Looks like TXs are also requested at the block level, so will need a DISTINCT here as well.

2023-07-25 00:21 UTC, forgxyz requested changes
2 possible solutions
1. Change the SELECT list in the streamline models where the request is block level to DISTINCT
2. Make 2 `retry` models, one that just gets block number while a second that gets tx hash

2023-07-25 01:00 UTC, WHYTEWYLL commented on models/silver/streamline/realtime/streamline__blocks_realtime.sql
> +    block_number,
Doesnt UNION take care of the duplicates?

2023-07-25 01:01 UTC, WHYTEWYLL commented on models/silver/streamline/realtime/streamline__blocks_realtime.sql
> +    block_number,
On the silver side, we also have the qualify on the model taking care of it. Isnt?

2023-07-26 18:13 UTC, merged